TV Show V.1.0
UbdaNam/TV-Show pull request #27
Opened 2023-04-21 18:24 UTC by UbdaNam

## What does this PR do?

This PR is raised to implement the following features: 👍 :
- [x] Set up webpack to bundle our web app.
- [x] Setup jest to add unit tests.
- [x] Add TV show list page.
- [x] Add like TV show functionality.
- [x] Add a detail page for a TV show.
- [x] Add a comment on a TV show.
- [x] Use REST for API interactions.
- [x] Add item counter function.
- [x] Add unit test for the item counter function.
- [x] Install buble to use es6 import and export. 😀 

## Description of the tasks completed 👇 

- [x] Add the HTML for the structure. 
- [x] Add the CSS file for the styling.
- [x] Add the JavaScript file for adding interactions.
- [x] Add unit tests for CRUD functions and DOM manipulation.
- [x] Use the linter tool that analyzes my source code to flag programming errors, bugs, stylistic errors, and suspicious constructs. 💯 
- [x] Use Flexbox a layout tool in CSS that helps you easily position HTML elements on the page.
- [x] Check the accessibility of this project which means that websites, tools, and technologies are designed and developed so that people with disabilities ♿ can use them. For more information about Web accessibility [Click here](https://github.com/microverseinc/curriculum-html-css/blob/main/accessibility.md)☺️
     

  
## How should it be tested

Clone the repository
```
git clone https://github.com/UbdaNam/TV-Show.git
```
Navigate to the folder
```
cd TV-Show
```
Checkout to the branch
```
git checkout dev
```
Run tests
```
npm test
```

#### Thanks for reviewing our PR 😊

2023-04-21 20:02 UTC, ridwanediallo requested changes
# Changes Required ♻️
## Hi team, 
![AlmostThereReachGIF](https://user-images.githubusercontent.com/55918904/191301799-36d07166-0e35-4582-a231-7a2d780f7783.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- Good commit messages. ✔


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 20:02 UTC, ridwanediallo commented on src/style.css
> +  align-items: center;
- [ ] You did an excellent job with the styling. However, I noticed some duplicate code in your `style.css` file. I would recommend using the `Don't Repeat Yourself` principle to make our code look cleaner and easier to maintain. 
Instead of repeating this at `line 30` to `line 32`, `line 49` to `line 51`, `line 61` to `line 63`, `line 84` to `line 86` ... , I propose the following :point_down:  in numerous places
```
  display: flex;
  justify-content: center;
  align-items: center;
```

let's make a class called 'flex-center,' for example, and add it to everywhere we want to have that style, so we don't have to write the same code over and over. like this :point_down: 
```
.flex-center {
   display: flex;
  justify-content: center;
  align-items: center;
}
```
Please ensure to fix that. 
After applying the change your `HTML` might be similar to this :point_down: 
```
  <header class="flex-center ">
    <nav>
      <ul>
        <li class="logo flex-center ">Movie <br> logo</li>
        <li class="flex-center ">Home</li>
        <li class="flex-center ">TV Shows</li>
        <li class="flex-center ">Contact</li>
      </ul>
    </nav>
  </header>

  <main class="main flex-center">
    <h1 class="show"></h1>
    <div id="movie">
    </div>
    <section class="details">
    </section>
  </main>
```

2023-04-21 20:02 UTC, ridwanediallo commented on src/style.css
> +  align-items: center;
- [ ] The same can be said for these two lines of code, which are repealing in three different places for the `footer`, `.button-container`, `.genres` and `like-btn`.Please make sure to correct this. I recommend doing it the same way I suggested at the top. :ok_hand: 😊
```
.flex-align-center {
  display: flex;
  align-items: center;
}
```

- [ ] Last but not least, please review your code to ensure that the same code does not appear in multiple places. 😊

2023-04-22 09:09 UTC, codepantha approved these changes
# STATUS: APPROVED 🟢 ✔️ 

## Hi @UbdaNam 👋, 

Great work on making the changes requested by the previovs reviewer 👏 
Your project is now complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/5oGIdt1xapQ76/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-22 09:17 UTC, merged